CREATE TABLE role (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle character varying(100) NOT NULL
);

CREATE TABLE utilisateur (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom character varying(150) NOT NULL,
    email character varying(150) NOT NULL UNIQUE,
    motdepasse character varying(255) NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT fk_utilisateur_role FOREIGN KEY (role_id) REFERENCES role(id)
);

CREATE TABLE client (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom character varying(150) NOT NULL,
    telephone character varying(50),
    adresse text,
    encourstotal numeric(12,2) DEFAULT 0.00,
    limitecredit numeric(8,2)
);

CREATE TABLE fournisseur (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom character varying(150) NOT NULL,
    telephone character varying(50),
    soldecompte numeric(12,2) DEFAULT 0.00,
    adresse character varying(50)
);

CREATE TABLE produit (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle character varying(200) NOT NULL,
    prixunitaire numeric(12,2) NOT NULL,
    stockactuel integer DEFAULT 0 NOT NULL,
    seuilalerterupture integer DEFAULT 5
);

CREATE TABLE approvisionnement (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dateapprovisionnement timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    couttotal numeric(12,2) NOT NULL,
    referencebon character varying(100),
    utilisateur_id integer NOT NULL,
    fournisseur_id integer NOT NULL,
    CONSTRAINT fk_appro_fournisseur FOREIGN KEY (fournisseur_id) REFERENCES fournisseur(id),
    CONSTRAINT fk_appro_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id)
);

CREATE TABLE ligneapprovisionnement (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantitecommandee integer NOT NULL,
    prixachatunitaire numeric(12,2) NOT NULL,
    approvisionnement_id integer NOT NULL,
    produit_id integer NOT NULL,
    quantiterecu numeric(8,2),
    CONSTRAINT fk_ligneappro_appro FOREIGN KEY (approvisionnement_id) REFERENCES approvisionnement(id) ON DELETE CASCADE,
    CONSTRAINT fk_ligneappro_produit FOREIGN KEY (produit_id) REFERENCES produit(id)
);

CREATE TABLE vente (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datevente timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    montanttotal numeric(12,2) NOT NULL,
    montantencaisse numeric(12,2) NOT NULL,
    typepaiement character varying(50) NOT NULL,
    statutpaiement character varying(50) NOT NULL,
    utilisateur_id integer NOT NULL,
    client_id integer NOT NULL,
    CONSTRAINT fk_vente_client FOREIGN KEY (client_id) REFERENCES client(id),
    CONSTRAINT fk_vente_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES utilisateur(id)
);

CREATE TABLE lignevente (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantite integer NOT NULL,
    prixunitaire numeric(12,2) NOT NULL,
    vente_id integer NOT NULL,
    produit_id integer NOT NULL,
    CONSTRAINT fk_lignevente_produit FOREIGN KEY (produit_id) REFERENCES produit(id),
    CONSTRAINT fk_lignevente_vente FOREIGN KEY (vente_id) REFERENCES vente(id) ON DELETE CASCADE
);

CREATE TABLE dette (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    montantinitial numeric(12,2) NOT NULL,
    resteapayer numeric(12,2) NOT NULL,
    dateecheance date,
    estsoldee boolean DEFAULT false NOT NULL,
    venteid integer,
    CONSTRAINT dette_venteid_fkey FOREIGN KEY (venteid) REFERENCES vente(id)
);

CREATE TABLE paiementdette (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    montantpaye numeric(12,2) NOT NULL,
    datepaiement timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    methodepaiement character varying(50) NOT NULL,
    dette_id integer NOT NULL,
    CONSTRAINT fk_paiementdette_dette FOREIGN KEY (dette_id) REFERENCES dette(id) ON DELETE CASCADE
);